# Generated by Django 4.2.20 on 2025-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='toppings',
        ),
        migrations.AlterUniqueTogether(
            name='orderitemtopping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitemtopping',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemtopping',
            name='topping',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderItemTopping',
        ),
    ]
