# Generated by Django 4.2.20 on 2025-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
